Support the CML 2.3 node_definitions response structure
CiscoDevNet/virlutils pull request #133
Opened 2021-12-16 06:33 UTC by tombry

The node definitions returned by the GET node_definitions API in
CML 2.3 no longer nest the node def details  under a "data" property.
I also added some additional tests for `definitions nodes ls`.

This change is only really needed when CML 2.3 is released, but I tested 
that it works with CML 2.2.  The only expected breakage would be if 
anyone is using a custom "node_def" viewer plugin with CML 2.2 or earlier.

2021-12-16 15:22 UTC, xorrkaz requested changes
Looks good for the most part.  Just some formatting needed.

2021-12-16 15:22 UTC, xorrkaz commented on tests/v2/definitions.py
> +            with open(os.path.join(os.path.dirname(__file__), "static/response_get_node_defs.json"), 'rb') as fh_node_defs:
Please format all code with black.

2021-12-16 15:23 UTC, xorrkaz commented
BTW, thanks for the unit tests.  You're my new favorite contributor.

2021-12-17 19:03 UTC, tombry commented on tests/v2/definitions.py
> +            with open(os.path.join(os.path.dirname(__file__), "static/response_get_node_defs.json"), 'rb') as fh_node_defs:
Done.

2021-12-17 19:06 UTC, tombry commented
> BTW, thanks for the unit tests. You're my new favorite contributor.

Heh, thanks.  But how *else* would I know when I'm done?  😉

2021-12-17 19:12 UTC, tombry commented on virl/cli/definitions/nodes/ls/commands.py
> +    defs = [f["data"] if "data" in f else f for f in defs_orig]
Note that I could do this the other way around.  That is, I defaulted to assuming the latest version and then adding some code to handle legacy data, but I could do it the other way around.  That is, I could transform the new, flattened data structure into the legacy, nested structure.  If I did that, then the new version of virlutils would not break existing `ViewerPlugin(viewer="node_def")` plugins.  The downside is that it would mean that anyone writing a new plugin would need to continue using the legacy, nested structure until virlutils decides to switch to the new, flattened data structure.

2021-12-18 17:26 UTC, xorrkaz commented on tests/v2/definitions.py
> +            with open(os.path.join(os.path.dirname(__file__), "static/response_get_node_defs.json"), 'rb') as fh_node_defs:
Thanks.

2021-12-18 17:27 UTC, xorrkaz commented on virl/cli/definitions/nodes/ls/commands.py
> +    defs = [f["data"] if "data" in f else f for f in defs_orig]
I think you made the right choice.  You know I'm not happy breaking backwards compat, but I see no reason to carry technical debt here if the damage has been done upstream.  Moreover, I'm not sure anyone has written any plugins, let alone any for listing node defs.

2021-12-18 17:37 UTC, merged