Feat cml tmux
CiscoDevNet/virlutils pull request #143
Opened 2023-10-30 17:35 UTC by sgherdao

Since we are it, time to stop procrastinating and submit that PR for tmux support :)

```
This commit introduce a new command 'cml tmux'
It allows users to connect to multiple node consoles using 'tmux'. 
It creates a new 'tmux' session with the lab title and the first 4 characters of the lab ID.

The `--group` option offers two grouping choices:
- 'panes': Group all connections within a single 'tmux' window. (default)
- 'windows': Represent each connection as an individual 'tmux' window.

Version 2 only.
```

2023-10-31 09:30 UTC, xorrkaz requested changes

2023-10-31 09:30 UTC, xorrkaz commented on virl/about.py
> +__version__ = "1.4.3"
Please do not bump version yourself.

2023-10-31 09:30 UTC, xorrkaz commented on requirements.txt
> +libtmux
Is this also required for testing?

2023-10-31 10:28 UTC, sgherdao commented on virl/about.py
> +__version__ = "1.4.3"
Sorry, I based my branch out of `master`, do you want me to change it to 1.4.2?

2023-10-31 10:28 UTC, sgherdao commented on requirements.txt
> +libtmux
right :)!

2023-10-31 15:43 UTC, xorrkaz commented on requirements.txt
> +libtmux
Then it needs to be in test-requirements.txt.

2023-10-31 15:44 UTC, xorrkaz commented on virl/about.py
> +__version__ = "1.4.3"
joe-dev should have 1.4.3.  I see it in my pull.

2023-10-31 16:06 UTC, sgherdao commented on virl/about.py
> +__version__ = "1.4.3"
So we good?

2023-10-31 16:07 UTC, sgherdao commented on requirements.txt
> +libtmux
Committed already!
https://github.com/CiscoDevNet/virlutils/pull/143/commits/2b9338537f368dffbaa9688d41ccfe985cb09e3c

2023-11-01 08:50 UTC, xorrkaz approved these changes

2023-11-01 08:50 UTC, merged