fix(152): cml ls --all-users display wrong owner
CiscoDevNet/virlutils pull request #154
Opened 2024-06-27 20:46 UTC by sgherdao

alternative fix to #152 (other PR #153 :

- inside `ls` command, make 1 API call to get users and create a mapping owner_id (uuid)-> username
- updated `list_lab_table` and `print_table` signatures to take the `ownerids_usernames` mapping
- add new mock for `GET /users` in `MockCMLServer`

2024-06-29 08:49 UTC, xorrkaz requested changes
I like the simplicity of this approach, but the plugin API needs to change.

2024-06-29 08:49 UTC, xorrkaz commented on virl/cli/ls/commands.py
>          pl.visualize(labs=labs, cached_labs=cached_labs)
I think the API needs to change here as well.

2024-06-29 08:49 UTC, xorrkaz commented on virl/cli/ls/commands.py
>          pl.visualize(labs=labs, cached_labs=cached_labs)
This would also mean a doc change.

2024-06-29 09:32 UTC, sgherdao commented
Another way, to avoid the function signature change, we could set an attribute to the lab object:

        setattr(lab, "owner_username", ownerids_usernames[lab.owner])
 or equivalent
        lab.owner_username

but I am not sure how you feel about that

2024-06-30 10:16 UTC, xorrkaz commented
No, I don't like this as it changes the underlying CML API.  That's more surprising for plugin developers.  I like your map approach.

2024-07-01 00:48 UTC, sgherdao commented
Indeed, a bit hackish. I have found some bugs with the users and groups, plus plugin doc is missing. I have the changes staged. Happy to submit another Issue and/or PR or commit here.

2024-07-06 10:28 UTC, merged